# -*- coding: utf-8 -*-
"""16aug2023.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q46xZcHqGWWPzLGgA6bWAq6K-F7a-oUi
"""

#1 for checking,2 for  insert,3 for delete,4 for print list,0 for exit
name=["satyam","shyam","rahul","rohit","mohit"]
a=1
while a!=0:
    a=int(input("1 for checking,2 for insert,3 for delete,4 for print list,0 for exit"))
    if a==1:
      n=input("enter your name :")
      if n in name:
        print("yes your name is in list:")
      else:
        print("your name is not there")
    elif a==2:
        n=input("enter your name for inserting in list")
        name.append(n)
    elif a==3:
      n=input("enter your name deleting ")
      name.append(n)
    elif a==4:
      print ("name")

mylist=[10,20,30,"hey","hello"]
print(type(mylist))

mylist=[10,20,30,"hey","hello"]
mylist[0:4]

mylist=[10,20,30,"hey","hello"]
mylist[0]=100
print(mylist)

mylist=[10,20,30,"hey","hello"]
mylist[0:2]=[100,101]
print(mylist)

mylist=[10,20,30,"hey","hello"]
mylist.append(99)
print(mylist)
# append main 2 elements nhi de sakte

mylist=[10,20,30,"hey","hello"]
mylist.extend(["hey"])
print(mylist)

mylist=[10,20,30,"hey","hello"]
mylist.extend([100,101,102])
print(mylist)
# extend method m humko itreble dena pdta h

mylist=[10,20,30,"hey","hello"]
mylist.pop()
print(mylist)
#pop method se last element delete hota h
# pop main index position dete h

mylist=[10,20,30,"hey","hello"]
last_element=mylist.pop()

last_element

mylist=[10,20,30,"hey","hello"]
last_element=mylist.pop(-2)

last_element

mylist=[10,20,30,"hey","hello"]
mylist.remove(20)
print(mylist)
#remove m element batana pdta h ki konsa element dlt krna h

mylist=[10,20,30,"hey","hello"]
mylist.remove(20)
print(id(mylist[0]))

del mylist[0]
print(mylist)

mylist=[10,20,30,"hey","hello"]
mylist.count(10)
# count batata h ki element kitni bar aaya

#sort method sirf jab use use hoga jab same type ka data hoga agar alag alag hua to sort method nhi chalega like int int ok but int str not ok it will not run

mylist=[10,20,30,100,8,9,22]
mylist.sort()
print(mylist)

mylist=[10,20,21,30,40,77]
for var in mylist:
  print(var)

index=0
while(index < len(mylist)):
  print(index,mylist[index])
  index+=1

x="hey"
len(x)
x[2]

index=0
count=len(x)
while(index < count):
  print(index, x[index])
  index+=1

mylist=[10,20,21,30,40,77]
index=0
while(index < len(mylist)):
  if(mylist[index]%2==0):
      mylist[index]=mylist[index]+5
      index+=1

mylist=[10,20,21,30,40,77]
index=0
while(index < len(mylist)):
  if(mylist[index]%2==0):
      print(index,mylist[index])
  index+=1

mylist=[10,20,21,30,40,77]
index=0
while(index < len(mylist)):

    if(mylist[index]%2==0):
      mylist[index]=mylist[index]+5
    index+=1

mylist=[10,20,"hey","tushar"]
strlist=[]
for data in mylist:
  if(type(data) is str):
    print(data,data[1:])
    strlist.append(data[1:])
print(data)

#task
#1 create a program to identify all the uniques word or elements frm list and insert all the duplicate elements in other list
#2 create a program to get string element which have more than 2 vowels and append it into the vowellist
#3 now write a program to remove those element from the list which are not float or have any vowel in their words using while loop.
#4 create a tuple containing multiple elements and agar element integer hua and is a multiple of 2 and 3 then we will insert that element in to a list otherwise insert in to new list

# tuple: immutable : email
# list mutable: name,address
# tuple app parentheses laga k bana skte h ya single element ko comma se bana sakte h
#https:\\bit.ly/44NHOPh

mylist=[10,20,30,["hey","hello"]]
mylist

mylist=[10,20,30,["hey","hello"]]
mylist[-1]

mylist=[10,20,30,["hey","hello"]]
mylist[-1][-1]

mylist=[10,20,30,["hey","hello"]]
x=mylist[-1][-1]
print(x)

mylist=[10,20,30,["hey","hello"]]
mylist[-1][0]

#create a tuple containing multiple elements and agar element integer hua and is a multiple of 2 and 3 then we will insert that element in to a list otherwise insert in to new list
my_tuple=10,20,30,40,50,60,8,15,18,12,"hey","hello"
nor=[]
not_nor=[]

for element in mytuple:
    if(type(element)==int):
      if element%2==0 or element %3==0:
        nor.append(element)
      else:
        not_nor.append(element)
    else:
       not_nor.append(element)
print("elements divisible by 2 or 3:",nor)
print("other element:",not_nor)

mytuples=mytuple
(id(my_tuple))

my_tuple = 10, 20, 30, 40, 50, 60, 8, 15, 18, 12, "hey", "hello"

nor = [element for element in my_tuple if isinstance(element, int) and (element % 2 == 0 or element % 3 == 0)]
not_nor = [element for element in my_tuple if not (isinstance(element, int) and (element % 2 == 0 or element % 3 == 0))]

print("elements divisible by 2 or 3:", nor)
print("other elements:", not_nor)

mytuples = my_tuple
print("Memory address of my_tuple:", id(my_tuple))

my_tuple = 10, 20, 30, 40, 50, 60, 8, 15, 18, 12, "hey", "hello"

nor = [element for element in my_tuple if type(element) == int and (element % 2 == 0 or element % 3 == 0)]
not_nor = [element for element in my_tuple if not (type(element) == int and (element % 2 == 0 or element % 3 == 0))]

print("elements divisible by 2 or 3:", nor)
print("other elements:", not_nor)

mytuples = my_tuple
print("Memory address of my_tuple:", id(my_tuple))

#1 create a program to identify all the uniques word or elements frm list and insert all the duplicate elements in other list
input_list = [10, 20, 30, 20, 40, 50, 10, 60, 70, 30, 80, 40]
unique_elements = []
duplicate_elements = []

for element in input_list:
    if input_list.count(element) > 1:
        if element not in duplicate_elements:
            duplicate_elements.append(element)
    else:
        unique_elements.append(element)

print("Unique elements:", unique_elements)
print("Duplicate elements:", duplicate_elements)

#2 create a program to get string element which have more than 2 vowels and append it into the vowel list
a=str(input("enter the sentence:"))
i=0
j=['a','e','i','o','u']
for char in a:
    if char in j:
        i=i+1
print(i)

sentence = input("Enter the sentence: ")
vowel_list = []
vowels = 'aeiouAEIOU'

words = sentence.split()

for word in words:
    vowel_count = 0
    for char in word:
        if char in vowels:
            vowel_count += 1
    if vowel_count > 2:
        vowel_list.append(word)

print("Words with more than 2 vowels:", vowel_list)

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

x.intersection_update(y)

print(x)

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

x.symmetric_difference_update(y)

print(x)

x = {"apple", "banana", "cherry", True}
y = {"google", 1, "apple", 2}

z = x.symmetric_difference(y)

#now write a program to remove those element from the list which are not float or have any vowel in their words using while loop.


input_list = input("Enter a list of elements separated by spaces: ").split()
filtered_list = []

i = 0
while i < len(input_list):
    element = input_list[i]

    if (isinstance(element, float) or
        (isinstance(element, str) and all(char not in "aeiouAEIOU" for char in element))):
        filtered_list.append(element)

    i += 1

print("Original List:", input_list)
print("Filtered List:", filtered_list)

